app = "testnet-walloop-engine"
primary_region = "iad"

[build]
  dockerfile = "Dockerfile"

[env]
  DB_SCHEMA = "engine"
  MANAGEMENT_TRACING_ENABLED = "false"
  OTEL_TRACES_EXPORTER = "none"
  EUREKA_CLIENT_ENABLED = "true"
  EUREKA_CLIENT_SERVICE_URL = "http://testnet-walloop-edge.internal:8761/eureka"
  WALLOOP_WALLET_BASE_URL = "http://testnet-walloop-wallet.internal:8080"
  LIQUID_RPC_URL = "testnet-walloop-liquid-node.internal:7041"
  SIDESHIFT_BASE_URL = "https://sideshift.ai/api/v2"
  FIXEDFLOAT_BASE_URL = "https://ff.io/api/v2"
  BOLTZ_BASE_URL = "https://api.boltz.exchange/v2"
  BOLTZ_CLAIM_SIGNER_URL = "http://testnet-walloop-lightning-signer.internal:3000"
  WALLOOP_LIGHTNING_LSP_BASE_URL = "https://api.amboss.space"
  COINCAP_BASE_URL = "https://rest.coincap.io/v3"
  LND_GRPC_HOST = "[fdaa:3a:c627:a7b:5d3:96a9:d10e:2]"
  LND_GRPC_PORT = "10009"
  SPRING_RABBITMQ_SSL_ENABLED = "true"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

  [[http_service.checks]]
    type = "http"
    interval = "15s"
    timeout = "2s"
    grace_period = "120s"
    method = "GET"
    path = "/actuator/health"

[deploy]
  wait_timeout = "5m"

[vm]
  size = "shared-cpu-2x"
  memory = "1024mb"
