ALTER TABLE engine.sideshift_shift
    ADD COLUMN IF NOT EXISTS deposit_address VARCHAR(200),
    ADD COLUMN IF NOT EXISTS deposit_network VARCHAR(64),
    ADD COLUMN IF NOT EXISTS deposit_tx_id VARCHAR(200),
    ADD COLUMN IF NOT EXISTS status VARCHAR(32) NOT NULL DEFAULT 'CREATED',
    ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    ADD COLUMN IF NOT EXISTS deposit_sent_at TIMESTAMPTZ,
    ADD COLUMN IF NOT EXISTS settled_at TIMESTAMPTZ;

UPDATE engine.sideshift_shift
SET status = 'CREATED',
    updated_at = NOW()
WHERE status IS NULL;
