ALTER TABLE engine.sideshift_pair_simulation
    ADD COLUMN IF NOT EXISTS amount VARCHAR(100),
    ADD COLUMN IF NOT EXISTS last_balance VARCHAR(100),
    ADD COLUMN IF NOT EXISTS min VARCHAR(100),
    ADD COLUMN IF NOT EXISTS max VARCHAR(100),
    ADD COLUMN IF NOT EXISTS rate VARCHAR(100),
    ADD COLUMN IF NOT EXISTS deposit_coin VARCHAR(50),
    ADD COLUMN IF NOT EXISTS settle_coin VARCHAR(50),
    ADD COLUMN IF NOT EXISTS deposit_network VARCHAR(50),
    ADD COLUMN IF NOT EXISTS settle_network VARCHAR(50);

ALTER TABLE engine.sideshift_pair_simulation
    ALTER COLUMN response_payload DROP NOT NULL;
